### PR TITLE
#89: Support ssh repo's remote url (closes #89)

### LINKED ISSUE #89: Support git origins that are missing the suffix ".git"
## description
`smooth-release` fails at parsing `owner` and `repo` from a remote origin (`ssh` or `https`) that misses the `.git` suffix

## specs
instead of handling the `.git` suffix, we should replace it completely with a `.replace('.git', '')` so to ensure we work on a standardized version of git origin

## misc
https://github.com/buildo/smooth-release/blob/69cc2fc48baa716e7ecc50e6097c0542f217c9d4/src/utils.js#L117

### PR DESCRIPTION
**Pull request by ascariandrea**
Closes #89

### tests performed
Finally :) https://github.com/buildo/scriptoni/commit/a72600c9d1e9d3a386ac001f68285b953b3f4beb

EDIT (by @FrancescoCioria):
- isolated `getGithubOwnerAndRepo` and tested with
  - https **with** `.git` -> ✅ 
  - ssh **with** `.git` -> ✅ 
  - https **without** `.git` -> ✅ 
  - ssh **without** `.git` -> ✅ 

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.}

### CODE REVIEW

**Comment by FrancescoCioria** [comment]
@ascariandrea I tried on `master` and it already works correctly with both `https` and `ssh` (I've been using `ssh` since forever). I'm not convinced this PR is actually fixing anything...

**Comment by ascariandrea** [comment]
Then how could I have finally published `scriptoni`?

**Comment by FrancescoCioria** [comment]
> Then how could I have finally published `scriptoni`?

no idea, can you test that this function actually breaks on `master`?

**Comment by ascariandrea** [comment]
My output of `git config --get remote.origin.url` is `git@github.com:buildo/scriptoni` (missing the trailing `.git`) and I don't know why.
We can change the logic of this refactor by checking the existence of trailing `.git` or avoid support for such formed url.

**Pull request merged**
