### PR TITLE
#53: Changelog is committed after the tag (closes #53)

### LINKED ISSUE #53: Changelog is committed after the tag
At the moment, smooth-release generates two commits, the first with the version bump, the second one with the updated changelog. The git tag for the release is pointing to the first one, where the changelog has not been updated yet.

Example:
```
* d39311f (HEAD -> master, origin/master) Update CHANGELOG.md
* 79ec628 (tag: v0.4.1) 0.4.1
```

Ideally smooth-release should generate a single commit including both the version bump and the changelog update, and point the git tag to that commit.

### PR DESCRIPTION
**Pull request by FrancescoCioria**
Issue #53

### tests performed
- `./smooth-release --changelog`
  - correctly throws an error: "Error: CHANGELOG.md hasn't changed"
- mock `commitAndPush` (prefix every command with `echo`)
- run it with `{ hasIncreasedVersion: false, hasUpdatedChangelog: true }`
  - commit message is "Update CHANGELOG.md"
- run it with `{ hasIncreasedVersion: true, hasUpdatedChangelog: true }`
  - commit message is "6.0.0"  (current version taken from `package.json`) ✅ 
- run it with `{ hasIncreasedVersion: true, hasUpdatedChangelog: false }`
  - commit message is "6.0.0"  (current version taken from `package.json`) ✅ 
- mock only push steps, ensure "version" and "changelog" don't throw any error
- run `./smooth-release --no-npm-publish --no-gh-release --no-validations`
  - new commit "7.0.0" with updated package.json and CHANGELOG.md
  - new tag "v7.0.0"

### tests not performed (domain coverage)
I didn't run a complete `./smooth-release`

### CODE REVIEW

**Comment by FrancescoCioria** [comment]
@dhinus https://github.com/FrancescoCioria/smooth-release/issues/53#issuecomment-270179246

**Review by dhinus — CHANGES_REQUESTED** [review]
LGTM! 💯

I'll test this very soon with `contacthub-sdk-nodejs`.

Can you update the README ("What it does") to describe the new behaviour?

**Comment by FrancescoCioria** [comment]
> Can you update the README ("What it does") to describe the new behaviour?

sure, I'll do it!

**Comment by dhinus** [comment]
I tested this branch and it created a release successfully but [did not add the release title and release notes](https://github.com/contactlab/contacthub-sdk-nodejs/releases/tag/v0.1.0).

Also the [CHANGELOG](https://github.com/contactlab/contacthub-sdk-nodejs/blob/master/CHANGELOG.md) contains "Unreleased" instead of "v0.1.0".

This is the command I used:

`smooth-release --no-npm-publish minor`

**Comment by FrancescoCioria** [comment]
@dhinus I just run the same command and it worked without problems.
Only thing I noticed is that for you that was the first tag/release, may there's an issue with the first release!

I'll investigate (somehow)

**Comment by FrancescoCioria** [comment]
nope, it works also if you never made a release (or a tag).

Sorry, but i can't understand without some logs/screenshots :(

Right now my only hypothesis are:
1. internet error
2. your GitHub token is not valid for contactlab

If it happens again we can open an issue just for this (I didn't even touch the `gh-release` code in this PR)

**Comment by dhinus** [comment]
@FrancescoCioria that's weird. Let's try merging this pull request then, and I'll let you know if the same thing happens again!

**Review by dhinus — APPROVED** [review]

**Comment by dhinus** [comment]
> I tested this branch and it created a release successfully but did not add the release title and release notes.
> Also the CHANGELOG contains "Unreleased" instead of "v0.1.0".

@FrancescoCioria I had this problem again, and I _think_ it's related to the fact I was using `smooth-release minor` because it worked fine using `smooth-release 0.2.0`. I opened #68.

**Pull request merged**
