### PR TITLE
feat: allow to specify labels to "github.changelog.feature"

### PR DESCRIPTION
**Pull request by micooz**

### CODE REVIEW

**Comment by FrancescoCioria** [comment]
Hi @micooz, thank you for this PR! I'll review it shortly

**Review by FrancescoCioria — CHANGES_REQUESTED** [review]
With these changes, you're not simply allowing to use a specific label to identify a feature but you're actually requiring it.

Even more, if there is at least one issue without any label the whole script will fail.

What is exactly your pain point?
How would you like issues without any label to appear on the changelog?

**Comment by micooz** [comment]
Hi, @FrancescoCioria, I think it's weird to treat non-(bug/breaking) as `feature` if no `ignoredLabels` provided.

`bug`, `breaking` and `feature` should be at the same level, so labels is required for `feature` just as `bug` and `breaking` do.

Pass labels to `feature` explicitly **makes it clear** to know what kind of issues should be grouped.

Issues without any labels probably are not considered to be a change so it shouldn't appear in the changelog.

**Comment by FrancescoCioria** [comment]
Mmm, I don't agree for this simple reason: A chengelog with useless information is better than a changelog without important information.

With your implementation, If you forget to add the label "feature" your users will not see that feature while, with current implementation, if you forget to add a label to ignore an issue, your users will see a not-important issue.

The second option sounds much safer to me as a default.

Nevertheless I agree with you that devs should be able to overwrite this defaults and choose how issues without known labels should be treated.

Instead of changing the logic I would improve the config with a two new options:
one to decide the label for feature issues (def "feature"?) and the other option as an enum to decide how to treat issues with no known labels and treat it by default as "feature-issues".

With this implementation, in your case, you could pass to this hypothetical option "ignore" and so you'd be forced to pass the label "feature" (or whatever you choose in the config) to set an issue as a feature.

Would this be ok with you? :)

**Comment by micooz** [comment]
Sorry for my late, it seems a good idea. Looking forward to your enhancement!

**Comment by FrancescoCioria** [comment]
@micooz I opened https://github.com/buildo/smooth-release/issues/100
I hope i can work on it soon :)

**Pull request closed without merging**
